package br.com.dice_manager.core_design_system.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF235FA6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFd5e3ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001b3c)
val md_theme_light_secondary = Color(0xFF555f71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFd9e3f8)
val md_theme_light_onSecondaryContainer = Color(0xFF121c2b)
val md_theme_light_tertiary = Color(0xFF6e5676)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFf8d8fe)
val md_theme_light_onTertiaryContainer = Color(0xFF28132f)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfdfbff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfdfbff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFe0e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
val md_theme_light_outline = Color(0xFF74777f)

val md_theme_dark_primary = Color(0xFFa7c8ff)
val md_theme_dark_onPrimary = Color(0xFF003061)
val md_theme_dark_primaryContainer = Color(0xFF004788)
val md_theme_dark_onPrimaryContainer = Color(0xFFd5e3ff)
val md_theme_dark_secondary = Color(0xFFbdc7dc)
val md_theme_dark_onSecondary = Color(0xFF273141)
val md_theme_dark_secondaryContainer = Color(0xFF3d4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFd9e3f8)
val md_theme_dark_tertiary = Color(0xFFdbbce1)
val md_theme_dark_onTertiary = Color(0xFF3e2845)
val md_theme_dark_tertiaryContainer = Color(0xFF563e5d)
val md_theme_dark_onTertiaryContainer = Color(0xFFf8d8fe)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe3e2e6)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe3e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF43474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc4c6cf)
val md_theme_dark_outline = Color(0xFF8e9199)